package ai

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"backend/config"
	"backend/handlers"
	domainAI "backend/internal/domain/ai"
	"backend/internal/infra/rabbitmq/producer"
)

// ResponseNode represents a workflow canvas node generated by AI.
type ResponseNode struct {
	ID    string            `json:"id"`
	Type  string            `json:"type"`
	Label string            `json:"label"`
	X     int               `json:"x"`
	Y     int               `json:"y"`
	Doc   map[string]string `json:"doc"`
	Roles map[string]any    `json:"roles"`
}

// ResponseEdge represents a connecting edge between canvas nodes.
type ResponseEdge struct {
	ID    string `json:"id"`
	From  string `json:"from"`
	To    string `json:"to"`
	Label string `json:"label"`
}

// GeneratedFlowResult represents the structured workflow model output by AI.
type GeneratedFlowResult struct {
	Status      string         `json:"status"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Nodes       []ResponseNode `json:"nodes"`
	Edges       []ResponseEdge `json:"edges"`
}

// AICallFunc defines the function signature for calling the AI generation model.
type AICallFunc func(systemInstruction, prompt string, schema any) (string, error)

// DefaultAICaller points to an optional AI generation caller override (useful for mocks).
var DefaultAICaller AICallFunc

// ExecuteProcessAIFlowJob executes the heavy Gemini AI generation task, parses the result,
// and saves the output to the database via AIJobRepository.
func ExecuteProcessAIFlowJob(ctx context.Context, repo domainAI.AIJobRepository, job producer.AIJobPayload) (*domainAI.AIJob, error) {
	if repo != nil {
		_ = repo.UpdateJobStatus(ctx, job.JobID, domainAI.StatusProcessing, nil, "")
	}

	systemInstruction := `Anda adalah ahli pemodelan proses bisnis dan arsitek sistem teknis Flowak.
Tugas Anda mendesain alur kerja (workflow) lengkap dalam bentuk graf Node (langkah proses) dan Edge (sambungan/aliran) berdasarkan deskripsi pengguna.

Aturan Penting:
1. Buat 4 hingga 8 langkah (nodes) yang logis, berurutan, dan menyertakan aspek bisnis (actor, input, process, output, sla) serta aspek teknis untuk UI/UX, Frontend, dan Backend.
2. Tempatkan koordinat x dan y (grid kelipatan 40px) sedemikian rupa agar membentuk diagram alir yang indah dan tidak tumpang tindih. (Misal: Node pertama di x: 80, y: 150. Node berikutnya bergeser ke kanan x: 380, y: 150, dst. Jika ada percabangan, Anda bisa menyebarkan y).
3. Sambungkan node dengan Edge yang merujuk pada id node yang sesuai.
4. Pastikan response strictly valid JSON sesuai tipe skema yang diberikan.`

	promptTemplate := fmt.Sprintf(`Deskripsi Kebutuhan: "%s"

Silakan buatkan struktur node proses bisnis dan edges sesuai dengan deskripsi tersebut.`, job.Prompt)

	schema := map[string]any{
		"type": "OBJECT",
		"properties": map[string]any{
			"name": map[string]any{
				"type":        "STRING",
				"description": "Nama modul alur kerja yang representatif dan profesional",
			},
			"description": map[string]any{
				"type":        "STRING",
				"description": "Deskripsi singkat mengenai alur kerja fungsional ini",
			},
			"nodes": map[string]any{
				"type":        "ARRAY",
				"description": "Daftar node dalam diagram alir",
				"items": map[string]any{
					"type": "OBJECT",
					"properties": map[string]any{
						"tempId": map[string]any{"type": "STRING", "description": "ID sementara node (contoh: 'node_1', 'node_2')"},
						"type":   map[string]any{"type": "STRING", "description": "Tipe node: 'terminator' | 'process' | 'decision' | 'actor' | 'system'"},
						"label":  map[string]any{"type": "STRING", "description": "Label singkat representatif langkah alur (contoh: 'Validasi OTP')"},
						"x":      map[string]any{"type": "NUMBER", "description": "Koordinat horizontal di kanvas (kisaran 100 s.d 1400)"},
						"y":      map[string]any{"type": "NUMBER", "description": "Koordinat vertikal di kanvas (kisaran 100 s.d 800)"},
						"doc": map[string]any{
							"type":        "OBJECT",
							"description": "Aspek analisis fungsional bisnis",
							"properties": map[string]any{
								"actor":   map[string]any{"type": "STRING", "description": "Aktor utama (contoh: 'Pelanggan', 'Sistem', 'Admin')"},
								"input":   map[string]any{"type": "STRING"},
								"process": map[string]any{"type": "STRING"},
								"output":  map[string]any{"type": "STRING"},
								"rules":   map[string]any{"type": "STRING"},
								"system":  map[string]any{"type": "STRING"},
								"sla":     map[string]any{"type": "STRING"},
							},
						},
						"roles": map[string]any{
							"type": "OBJECT",
							"properties": map[string]any{
								"uiux": map[string]any{
									"type": "OBJECT",
									"properties": map[string]any{
										"assignee": map[string]any{"type": "STRING"},
										"status":   map[string]any{"type": "STRING"},
										"screen":   map[string]any{"type": "STRING"},
									},
								},
								"frontend": map[string]any{
									"type": "OBJECT",
									"properties": map[string]any{
										"assignee":  map[string]any{"type": "STRING"},
										"status":    map[string]any{"type": "STRING"},
										"component": map[string]any{"type": "STRING"},
										"route":     map[string]any{"type": "STRING"},
										"framework": map[string]any{"type": "STRING"},
									},
								},
								"backend": map[string]any{
									"type": "OBJECT",
									"properties": map[string]any{
										"assignee":   map[string]any{"type": "STRING"},
										"status":     map[string]any{"type": "STRING"},
										"method":     map[string]any{"type": "STRING"},
										"endpoint":   map[string]any{"type": "STRING"},
										"statusCode": map[string]any{"type": "STRING"},
									},
								},
							},
						},
					},
					"required": []string{"tempId", "type", "label", "x", "y"},
				},
			},
			"edges": map[string]any{
				"type":        "ARRAY",
				"description": "Daftar sambungan atau garis penghubung antar node alur kerja",
				"items": map[string]any{
					"type": "OBJECT",
					"properties": map[string]any{
						"from":  map[string]any{"type": "STRING"},
						"to":    map[string]any{"type": "STRING"},
						"label": map[string]any{"type": "STRING"},
					},
					"required": []string{"from", "to"},
				},
			},
		},
		"required": []string{"name", "description", "nodes", "edges"},
	}

	caller := DefaultAICaller
	if caller == nil {
		if config.ActiveConfig.GeminiAPIKey == "" {
			errMsg := "AI service is not configured; create the draft specification manually."
			if repo != nil {
				_ = repo.UpdateJobStatus(ctx, job.JobID, domainAI.StatusFailed, nil, errMsg)
			}
			return &domainAI.AIJob{
				ID:           job.JobID,
				Type:         job.Type,
				Status:       domainAI.StatusFailed,
				ErrorMessage: errMsg,
				UpdatedAt:    time.Now().UTC(),
			}, fmt.Errorf("%s", errMsg)
		}
		caller = handlers.CallGemini
	}

	resultText, err := caller(systemInstruction, promptTemplate, schema)
	if err != nil {
		if repo != nil {
			_ = repo.UpdateJobStatus(ctx, job.JobID, domainAI.StatusFailed, nil, err.Error())
		}
		return &domainAI.AIJob{
			ID:           job.JobID,
			Type:         job.Type,
			Status:       domainAI.StatusFailed,
			ErrorMessage: err.Error(),
			UpdatedAt:    time.Now().UTC(),
		}, err
	}

	var rawFlow struct {
		Name        string `json:"name"`
		Description string `json:"description"`
		Nodes       []struct {
			TempID string `json:"tempId"`
			Type   string `json:"type"`
			Label  string `json:"label"`
			X      int    `json:"x"`
			Y      int    `json:"y"`
			Doc    struct {
				Actor   string `json:"actor"`
				Input   string `json:"input"`
				Process string `json:"process"`
				Output  string `json:"output"`
				Rules   string `json:"rules"`
				System  string `json:"system"`
				Sla     string `json:"sla"`
			} `json:"doc"`
			Roles struct {
				Uiux struct {
					Assignee string `json:"assignee"`
					Status   string `json:"status"`
					Screen   string `json:"screen"`
				} `json:"uiux"`
				Frontend struct {
					Assignee  string `json:"assignee"`
					Status    string `json:"status"`
					Component string `json:"component"`
					Route     string `json:"route"`
					Framework string `json:"framework"`
				} `json:"frontend"`
				Backend struct {
					Assignee   string `json:"assignee"`
					Status     string `json:"status"`
					Method     string `json:"method"`
					Endpoint   string `json:"endpoint"`
					StatusCode string `json:"statusCode"`
				} `json:"backend"`
			} `json:"roles"`
		} `json:"nodes"`
		Edges []struct {
			From  string `json:"from"`
			To    string `json:"to"`
			Label string `json:"label"`
		} `json:"edges"`
	}

	if err := json.Unmarshal([]byte(resultText), &rawFlow); err != nil {
		parseErr := fmt.Errorf("failed to parse Gemini output: %w", err)
		if repo != nil {
			_ = repo.UpdateJobStatus(ctx, job.JobID, domainAI.StatusFailed, nil, parseErr.Error())
		}
		return &domainAI.AIJob{
			ID:           job.JobID,
			Type:         job.Type,
			Status:       domainAI.StatusFailed,
			ErrorMessage: parseErr.Error(),
			UpdatedAt:    time.Now().UTC(),
		}, parseErr
	}

	idMap := make(map[string]string)
	respNodes := make([]ResponseNode, 0, len(rawFlow.Nodes))
	for _, n := range rawFlow.Nodes {
		generatedID := "node_" + handlers.GenerateUUID()
		idMap[n.TempID] = generatedID

		uiuxAssignee := n.Roles.Uiux.Assignee
		if uiuxAssignee == "" {
			uiuxAssignee = "Rian"
		}
		feAssignee := n.Roles.Frontend.Assignee
		if feAssignee == "" {
			feAssignee = "Siti"
		}
		beAssignee := n.Roles.Backend.Assignee
		if beAssignee == "" {
			beAssignee = "Budi"
		}

		respNodes = append(respNodes, ResponseNode{
			ID:    generatedID,
			Type:  n.Type,
			Label: n.Label,
			X:     n.X,
			Y:     n.Y,
			Doc: map[string]string{
				"actor":   n.Doc.Actor,
				"input":   n.Doc.Input,
				"process": n.Doc.Process,
				"output":  n.Doc.Output,
				"rules":   n.Doc.Rules,
				"system":  n.Doc.System,
				"sla":     n.Doc.Sla,
			},
			Roles: map[string]any{
				"uiux": map[string]string{
					"assignee": uiuxAssignee,
					"status":   "planned",
					"screen":   n.Roles.Uiux.Screen,
					"link":     "",
				},
				"frontend": map[string]string{
					"assignee":  feAssignee,
					"status":    "planned",
					"component": n.Roles.Frontend.Component,
					"route":     n.Roles.Frontend.Route,
					"framework": n.Roles.Frontend.Framework,
					"link":      "",
				},
				"backend": map[string]string{
					"assignee":   beAssignee,
					"status":     "planned",
					"method":     n.Roles.Backend.Method,
					"endpoint":   n.Roles.Backend.Endpoint,
					"auth":       "",
					"request":    "",
					"response":   "",
					"statusCode": n.Roles.Backend.StatusCode,
				},
			},
		})
	}

	respEdges := make([]ResponseEdge, 0, len(rawFlow.Edges))
	for _, e := range rawFlow.Edges {
		fromID := idMap[e.From]
		toID := idMap[e.To]
		if fromID == "" || toID == "" {
			continue
		}
		respEdges = append(respEdges, ResponseEdge{
			ID:    "edge_" + handlers.GenerateUUID(),
			From:  fromID,
			To:    toID,
			Label: e.Label,
		})
	}

	flowResult := GeneratedFlowResult{
		Status:      "complete",
		Name:        rawFlow.Name,
		Description: rawFlow.Description,
		Nodes:       respNodes,
		Edges:       respEdges,
	}

	if repo != nil {
		_ = repo.UpdateJobStatus(ctx, job.JobID, domainAI.StatusCompleted, flowResult, "")
	}

	return &domainAI.AIJob{
		ID:        job.JobID,
		Type:      job.Type,
		Status:    domainAI.StatusCompleted,
		Prompt:    job.Prompt,
		Result:    flowResult,
		UpdatedAt: time.Now().UTC(),
	}, nil
}
